# MD013/line-length Line length
MD013: false

# MD014/commands-show-output Dollar signs used before commands without showing output
MD014: false

# MD033/no-inline-html Inline HTML (used in README.md)
MD033:
  allowed_elements:
    - sup
    - sub
    - code

# heading duplication is allowed for non-sibling headings (common in change logs)
MD024:
  siblings_only: true
