name: Check Docs & Overrides

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - name: Check Docs
        run: npm run export:docs
      - name: Check Overrides
        run: npm run export:overrides
