
name: Release

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  documentation:
    if: ${{ github.event.pull_request.merged == true }}
    name: Check Docs & Overrides
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 16.7
        uses: actions/setup-node@v2
        with:
          node-version: 16.7

      - name: Install NPM   
        run: npm install

      - name: Check Docs
        run: npm run export:docs
      - name: Check Overrides
        run: npm run export:overrides

  release:
    if: ${{ github.event.pull_request.merged == true }}
    needs: [documentation]
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 16.7
        uses: actions/setup-node@v2
        with:
          node-version: 16.7
      
      - name: Install NPM   
        run: npm install

      - name: Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
