name: Tests, Linter & Typecheck

on: pull_request

jobs:
  test:
    name: "Typechecking"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.7
        uses: actions/setup-node@v2
        with:
          node-version: 16.7

      - name: Install NPM dependencies
        run: npm install

      - uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Run Prettier
        run: npm run prettier:check

      - name: Run Type Checking
        run: tsc
